<?php

return [
    ["name"=> "Antipolo", "code"=> 102 ],
    ["name"=> "Bagumbayan", "code"=> 101 ],
    ["name"=> "Bacolod", "code"=> 218 ],
    ["name"=> "Baguio", "code"=> 153 ],
    ["name"=> "Balanga", "code"=> 139 ],
    ["name"=> "Bangued", "code"=> 155 ],
    ["name"=> "Batangas", "code"=> 131 ],
    ["name"=> "Butuan", "code"=> 175 ],
    ["name"=> "Calamba", "code"=> 111 ],
    ["name"=> "Calasiao", "code"=> 149 ],
    ["name"=> "Canlubang", "code"=> 128 ],
    ["name"=> "Candon", "code"=> 154 ],
    ["name"=> "Carlatan", "code"=> 152 ],
    ["name"=> "Cauayan", "code"=> 158 ],
    ["name"=> "Cebu Plant", "code"=> 216 ],
    ["name"=> "Consolacion", "code"=> 200 ],
    ["name"=> "Cotabato", "code"=> 183 ],
    ["name"=> "Daet", "code"=> 146 ],
    ["name"=> "Dasmariñas", "code"=> 109 ],
    ["name"=> "Davao DC", "code"=> 498 ],
    ["name"=> "Davao Plant", "code"=> 165 ],
    ["name"=> "Davao Plant 2", "code"=> 199 ],
    ["name"=> "General Santos", "code"=> 179 ],
    ["name"=> "Ilagan", "code"=> 156 ],
    ["name"=> "Iligan", "code"=> 176 ],
    ["name"=> "Ilocos", "code"=> 160 ],
    ["name"=> "Iloilo", "code"=> 220 ],
    ["name"=> "Lipa", "code"=> 130 ],
    ["name"=> "Legaspi", "code"=> 147 ],
    ["name"=> "Lucena", "code"=> 132 ],
    ["name"=> "Malolos", "code"=> 115 ],
    ["name"=> "Manila", "code"=> 96 ],
    ["name"=> "Meycauayan", "code"=> 112 ],
    ["name"=> "Misamis Oriental", "code"=> 680 ],
    ["name"=> "Naga DC", "code"=> 148 ],
    ["name"=> "Naga Plant", "code"=> 145 ],
    ["name"=> "Nueva Ecija", "code"=> 97 ],
    ["name"=> "Ormoc", "code"=> 223 ],
    ["name"=> "Pagadian", "code"=> 189 ],
    ["name"=> "Pampanga", "code"=> 138 ],
    ["name"=> "Paranaque", "code"=> 98 ],
    ["name"=> "Puerto Princesa", "code"=> 129 ],
    ["name"=> "Quezon City", "code"=> 100 ],
    ["name"=> "SanFernando", "code"=> 137 ],
    ["name"=> "Solano", "code"=> 157 ],
    ["name"=> "Sta.Rosa", "code"=> 106 ],
    ["name"=> "Tacloban", "code"=> 222 ],
    ["name"=> "Tagbilaran DC", "code"=> 567 ],
    ["name"=> "Tagbilaran Plant", "code"=> 234 ],
    ["name"=> "Tagum", "code"=> 167 ],
    ["name"=> "Tanza", "code"=> 108 ],
    ["name"=> "Tarlac", "code"=> 151 ],
    ["name"=> "Urdaneta", "code"=> 150 ],
    ["name"=> "Zambales", "code"=> 144 ],
    ["name"=> "Zamboanga DC", "code"=> 169 ],
    ["name"=> "Zamboanga Plant", "code"=> 184 ],
];